In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
df = pd.read_csv(
    "/content/drive/MyDrive/Research/KDDTrain+.txt",
    sep=",",
)

In [ ]:
df.head()

,0,tcp,ftp_data,SF,491,0.1,0.2,0.3,0.4,0.5,...,0.17,0.03,0.17.1,0.00.6,0.00.7,0.00.8,0.05,0.00.9,normal,20
0,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal,15
1,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune,19
2,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal,21
3,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal,21
4,0,tcp,private,REJ,0,0,0,0,0,0,...,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune,21

In [ ]:
df.describe()

,0,491,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,25,0.17,0.03,0.17.1,0.00.6,0.00.7,0.00.8,0.05,0.00.9,20
count,125972.000000,1.259720e+05,1.259720e+05,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,...,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000,125972.000000
mean,287.146929,4.556710e+04,1.977927e+04,0.000198,0.022688,0.000111,0.204411,0.001222,0.395739,0.279253,...,115.653725,0.521244,0.082952,0.148379,0.032543,0.284455,0.278487,0.118832,0.120241,19.504056
std,2604.525522,5.870354e+06,4.021285e+06,0.014086,0.253531,0.014366,2.149977,0.045239,0.489011,23.942137,...,110.702886,0.448950,0.188922,0.308998,0.112564,0.444785,0.445670,0.306559,0.319460,2.291512
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000
50%,0.000000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,63.000000,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000
75%,0.000000,2.760000e+02,5.160000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,21.000000
max,42908.000000,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,77.000000,5.000000,1.000000,7479.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,21.000000

Removing Difficulty level column

In [ ]:
df = df.drop(['20'], axis= 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125972 entries, 0 to 125971
Data columns (total 42 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   0         125972 non-null  int64
 1   tcp       125972 non-null  object
 2   ftp_data  125972 non-null  object
 3   SF        125972 non-null  object
 4   491       125972 non-null  int64
 5   0.1       125972 non-null  int64
 6   0.2       125972 non-null  int64
 7   0.3       125972 non-null  int64
 8   0.4       125972 non-null  int64
 9   0.5       125972 non-null  int64
 10  0.6       125972 non-null  int64
 11  0.7       125972 non-null  int64
 12  0.8       125972 non-null  int64
 13  0.9       125972 non-null  int64
 14  0.10      125972 non-null  int64
 15  0.11      125972 non-null  int64
 16  0.12      125972 non-null  int64
 17  0.13      125972 non-null  int64
 18  0.14      125972 non-null  int64
 19  0.15      125972 non-null  int64
 20  0.16      125972 non-null  int64
 21  0.18      125972 non-null  int64
 22  2         125972 non-null  int64
 23  2.1       125972 non-null  int64
 24  0.00      125972 non-null  float64
 25  0.00.1    125972 non-null  float64
 26  0.00.2    125972 non-null  float64
 27  0.00.3    125972 non-null  float64
 28  1.00      125972 non-null  float64
 29  0.00.4    125972 non-null  float64
 30  0.00.5    125972 non-null  float64
 31  150       125972 non-null  int64
 32  25        125972 non-null  int64
 33  0.17      125972 non-null  float64
 34  0.03      125972 non-null  float64
 35  0.17.1    125972 non-null  float64
 36  0.00.6    125972 non-null  float64
 37  0.00.7    125972 non-null  float64
 38  0.00.8    125972 non-null  float64
 39  0.05      125972 non-null  float64
 40  0.00.9    125972 non-null  float64
 41  normal    125972 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 40.4+ MB

Adding column names

In [ ]:
df.columns =  [
    "duration",
    "protocol_type",
    "service",
    "flag",
    "src_bytes",
    "dst_bytes",
    "land",
    "wrong_fragment",
    "urgent",
    "hot",
    "num_failed_logins",
    "logged_in",
    "num_compromised",
    "root_shell",
    "su_attempted",
    "num_root",
    "num_file_creations",
    "num_shells",
    "num_access_files",
    "num_outbound_cmds",
    "is_host_login",
    "is_guest_login",
    "count",
    "srv_count",
    "serror_rate",
    "srv_serror_rate",
    "rerror_rate",
    "srv_rerror_rate",
    "same_srv_rate",
    "diff_srv_rate",
    "srv_diff_host_rate",
    "dst_host_count",
    "dst_host_srv_count",
    "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate",
    "dst_host_serror_rate",
    "dst_host_srv_serror_rate",
    "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate",
    "class"
]

In [ ]:
df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0,tcp,private,S0,0,0,0,0,0,0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125968,8,udp,private,SF,105,145,0,0,0,0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal
125969,0,tcp,smtp,SF,2231,384,0,0,0,0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal
125970,0,tcp,klogin,S0,0,0,0,0,0,0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125971,0,tcp,ftp_data,SF,151,0,0,0,0,0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal

#Encoding

In [ ]:
oh = OneHotEncoder(sparse_output=False)

In [ ]:
df_tcp_trans = pd.DataFrame(oh.fit_transform(df[['protocol_type']]),columns= oh.get_feature_names_out(["protocol_type"]))

In [ ]:
df_REJ_trans = pd.DataFrame(oh.fit_transform(df[['flag']]),columns= oh.get_feature_names_out(["flag"]))

In [ ]:
df_private_trans = pd.DataFrame(oh.fit_transform(df[['service']]),columns= oh.get_feature_names_out(["service"]))

In [ ]:
df_transform = pd.DataFrame(oh.fit_transform(df[['class']]),columns= oh.get_feature_names_out(['class']))

In [ ]:
df = pd.concat([df,df_tcp_trans,df_private_trans,df_REJ_trans,df_transform],axis= 1)

In [ ]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,class_phf,class_pod,class_portsweep,class_rootkit,class_satan,class_smurf,class_spy,class_teardrop,class_warezclient,class_warezmaster
0,0,udp,other,SF,146,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,tcp,private,S0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,tcp,http,SF,232,8153,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,tcp,http,SF,199,420,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,tcp,private,REJ,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df = df.drop(['protocol_type','service','flag','class'],axis = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125972 entries, 0 to 125971
Columns: 145 entries, duration to class_warezmaster
dtypes: float64(122), int64(23)
memory usage: 139.4 MB

In [ ]:
print(list(df.columns))

['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'protocol_type_icmp', 'protocol_type_tcp', 'protocol_type_udp', 'service_IRC', 'service_X11', 'service_Z39_50', 'service_aol', 'service_auth', 'service_bgp', 'service_courier', 'service_csnet_ns', 'service_ctf', 'service_daytime', 'service_discard', 'service_domain', 'service_domain_u', 'service_echo', 'service_eco_i', 'service_ecr_i', 'service_efs', 'service_exec', 'service_finger', 'service_ftp', 'service_ftp_data', 'service_gopher', 'service_harvest', 'service_hostnames', 'service_http', 'service_http_2784', 'service_http_443', 'service_http_8001', 'service_imap4', 'service_iso_tsap', 'service_klogin', 'service_kshell', 'service_ldap', 'service_link', 'service_login', 'service_mtp', 'service_name', 'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn', 'service_netstat', 'service_nnsp', 'service_nntp', 'service_ntp_u', 'service_other', 'service_pm_dump', 'service_pop_2', 'service_pop_3', 'service_printer', 'service_private', 'service_red_i', 'service_remote_job', 'service_rje', 'service_shell', 'service_smtp', 'service_sql_net', 'service_ssh', 'service_sunrpc', 'service_supdup', 'service_systat', 'service_telnet', 'service_tftp_u', 'service_tim_i', 'service_time', 'service_urh_i', 'service_urp_i', 'service_uucp', 'service_uucp_path', 'service_vmnet', 'service_whois', 'flag_OTH', 'flag_REJ', 'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0', 'flag_S1', 'flag_S2', 'flag_S3', 'flag_SF', 'flag_SH', 'class_back', 'class_buffer_overflow', 'class_ftp_write', 'class_guess_passwd', 'class_imap', 'class_ipsweep', 'class_land', 'class_loadmodule', 'class_multihop', 'class_neptune', 'class_nmap', 'class_normal', 'class_perl', 'class_phf', 'class_pod', 'class_portsweep', 'class_rootkit', 'class_satan', 'class_smurf', 'class_spy', 'class_teardrop', 'class_warezclient', 'class_warezmaster']

In [ ]:
df

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,class_phf,class_pod,class_portsweep,class_rootkit,class_satan,class_smurf,class_spy,class_teardrop,class_warezclient,class_warezmaster
0,0,146,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,232,8153,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,199,420,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125968,8,105,145,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125969,0,2231,384,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125970,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125971,0,151,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
       'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised',
       ...
       'class_phf', 'class_pod', 'class_portsweep', 'class_rootkit',
       'class_satan', 'class_smurf', 'class_spy', 'class_teardrop',
       'class_warezclient', 'class_warezmaster'],
      dtype='object', length=145)

#Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
df['duration'] = ss.fit_transform(df[['duration']])
df['src_bytes'] = ss.fit_transform(df[['src_bytes']])
df['dst_bytes'] = ss.fit_transform(df[['dst_bytes']])
df['count'] = ss.fit_transform(df[['count']])
df['srv_count'] = ss.fit_transform(df[['srv_count']])
df['dst_host_count'] = ss.fit_transform(df[['dst_host_count']])
df['dst_host_srv_count'] = ss.fit_transform(df[['dst_host_srv_count']])
df['dst_host_same_srv_rate'] = ss.fit_transform(df[['dst_host_same_srv_rate']])
df['dst_host_diff_srv_rate'] = ss.fit_transform(df[['dst_host_diff_srv_rate']])
df['dst_host_same_src_port_rate'] = ss.fit_transform(df[['dst_host_same_src_port_rate']])
df['dst_host_srv_diff_host_rate'] = ss.fit_transform(df[['dst_host_srv_diff_host_rate']])
df['dst_host_serror_rate'] = ss.fit_transform(df[['dst_host_serror_rate']])
df['dst_host_srv_serror_rate'] = ss.fit_transform(df[['dst_host_srv_serror_rate']])
df['dst_host_rerror_rate'] = ss.fit_transform(df[['dst_host_rerror_rate']])
df['dst_host_srv_rerror_rate'] = ss.fit_transform(df[['dst_host_srv_rerror_rate']])
df['wrong_fragment'] = ss.fit_transform(df[['wrong_fragment']])
df['urgent'] = ss.fit_transform(df[['urgent']])
df['hot'] = ss.fit_transform(df[['hot']])
df['num_failed_logins'] = ss.fit_transform(df[['num_failed_logins']])
df['num_compromised'] = ss.fit_transform(df[['num_compromised']])
df['root_shell'] = ss.fit_transform(df[['root_shell']])
df['su_attempted'] = ss.fit_transform(df[['su_attempted']])
df['num_root'] = ss.fit_transform(df[['num_root']])
df['num_file_creations'] = ss.fit_transform(df[['num_file_creations']])
df['num_shells'] = ss.fit_transform(df[['num_shells']])
df['num_access_files'] = ss.fit_transform(df[['num_access_files']])
df['num_outbound_cmds'] = ss.fit_transform(df[['num_outbound_cmds']])
df['is_host_login'] = ss.fit_transform(df[['is_host_login']])
df['is_guest_login'] = ss.fit_transform(df[['is_guest_login']])
df['serror_rate'] = ss.fit_transform(df[['serror_rate']])
df['srv_serror_rate'] = ss.fit_transform(df[['srv_serror_rate']])
df['rerror_rate'] = ss.fit_transform(df[['rerror_rate']])
df['srv_rerror_rate'] = ss.fit_transform(df[['srv_rerror_rate']])
df['same_srv_rate'] = ss.fit_transform(df[['same_srv_rate']])
df['diff_srv_rate'] = ss.fit_transform(df[['diff_srv_rate']])
df['srv_diff_host_rate'] = ss.fit_transform(df[['srv_diff_host_rate']])
df['logged_in'] = ss.fit_transform(df[['logged_in']])

In [ ]:
df['duration'].head()

0   -0.11025
1   -0.11025
2   -0.11025
3   -0.11025
4   -0.11025
Name: duration, dtype: float64

In [ ]:
df.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
       'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised',
       ...
       'class_phf', 'class_pod', 'class_portsweep', 'class_rootkit',
       'class_satan', 'class_smurf', 'class_spy', 'class_teardrop',
       'class_warezclient', 'class_warezmaster'],
      dtype='object', length=145)

In [ ]:
df

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,class_phf,class_pod,class_portsweep,class_rootkit,class_satan,class_smurf,class_spy,class_teardrop,class_warezclient,class_warezmaster
0,-0.110250,-0.007737,-0.004919,0,-0.089487,-0.007736,-0.095076,-0.027023,-0.809267,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.110250,-0.007762,-0.004919,0,-0.089487,-0.007736,-0.095076,-0.027023,-0.809267,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.110250,-0.007723,-0.002891,0,-0.089487,-0.007736,-0.095076,-0.027023,1.235686,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.110250,-0.007728,-0.004814,0,-0.089487,-0.007736,-0.095076,-0.027023,1.235686,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.110250,-0.007762,-0.004919,0,-0.089487,-0.007736,-0.095076,-0.027023,-0.809267,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,-0.110250,-0.007762,-0.004919,0,-0.089487,-0.007736,-0.095076,-0.027023,-0.809267,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125968,-0.107178,-0.007744,-0.004883,0,-0.089487,-0.007736,-0.095076,-0.027023,-0.809267,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125969,-0.110250,-0.007382,-0.004823,0,-0.089487,-0.007736,-0.095076,-0.027023,1.235686,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125970,-0.110250,-0.007762,-0.004919,0,-0.089487,-0.007736,-0.095076,-0.027023,-0.809267,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125971,-0.110250,-0.007737,-0.004919,0,-0.089487,-0.007736,-0.095076,-0.027023,1.235686,-0.011664,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#Model Training / Validation

Splitting into train, test and validaiton sets

In [ ]:
from sklearn.model_selection import train_test_split
X = df.iloc[:,:122]
y = df.iloc[:,122:]

X_temp, X_test, y_temp, y_test = train_test_split(
    X, y,
    test_size=0.2,          #80% temp, 20% test
    random_state=42
)

In [ ]:
X_train , X_val, y_train, y_val = train_test_split(
    X_temp, y_temp,
    test_size=0.2,          #80% train, 20% val
    random_state=42
)

In [ ]:
y_test.shape
#y_train.shape

(25195, 23)

#Random Forest Training

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    n_jobs=-1,
    random_state=42
)
rf_clf.fit(X_train, y_train)
y_val_pred_rf = rf_clf.predict(X_val)

print("Random Forest (val):")
print(classification_report(y_val, y_val_pred_rf))

Random Forest (val):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       143
           1       1.00      0.50      0.67         4
           2       0.00      0.00      0.00         2
           3       1.00      1.00      1.00         7
           4       0.00      0.00      0.00         2
           5       1.00      0.98      0.99       591
           6       1.00      0.50      0.67         2
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         0
           9       1.00      1.00      1.00      6590
          10       0.97      0.99      0.98       203
          11       1.00      1.00      1.00     10798
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         0
          14       1.00      1.00      1.00        31
          15       1.00      0.99      1.00       471
          16       0.00      0.00      0.00         1
          17       1.00      0.98      0.99       569
          18       1.00      1.00      1.00       454
          19       0.00      0.00      0.00         0
          20       1.00      1.00      1.00       147
          21       0.99      0.97      0.98       136
          22       1.00      0.33      0.50         3

   micro avg       1.00      1.00      1.00     20156
   macro avg       0.65      0.58      0.60     20156
weighted avg       1.00      1.00      1.00     20156
 samples avg       1.00      1.00      1.00     20156

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:

y_test_pred_rf = rf_clf.predict(X_test)

In [ ]:

print("Random Forest (test):")
print(classification_report(y_test, y_test_pred_rf))

Random Forest (test):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       201
           1       1.00      0.71      0.83         7
           2       0.00      0.00      0.00         0
           3       1.00      0.79      0.88        14
           4       1.00      1.00      1.00         2
           5       1.00      0.99      1.00       743
           6       0.50      0.50      0.50         2
           7       0.00      0.00      0.00         3
           8       0.00      0.00      0.00         1
           9       1.00      1.00      1.00      8238
          10       0.98      0.99      0.99       298
          11       1.00      1.00      1.00     13386
          12       0.00      0.00      0.00         1
          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00        36
          15       1.00      0.99      1.00       583
          16       0.00      0.00      0.00         2
          17       1.00      0.99      0.99       749
          18       1.00      1.00      1.00       551
          19       0.00      0.00      0.00         1
          20       1.00      1.00      1.00       196
          21       0.99      0.95      0.97       176
          22       1.00      0.75      0.86         4

   micro avg       1.00      1.00      1.00     25195
   macro avg       0.72      0.68      0.70     25195
weighted avg       1.00      1.00      1.00     25195
 samples avg       1.00      1.00      1.00     25195

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
print(type(y_test), getattr(y_test, "shape", None))

<class 'pandas.core.frame.DataFrame'> (25195, 23)

In [ ]:
print(type(y_test_pred_rf), getattr(y_test_pred_rf, "shape", None))

<class 'numpy.ndarray'> (25195, 23)

In [ ]:
# Converting to 1-D label arrays
y_test_1d = np.argmax(y_test.values, axis=1)

y_test_pred_1d = np.argmax(y_test_pred_rf, axis=1)

Confusion Matrix

In [ ]:
cm = confusion_matrix(y_test_1d, y_test_pred_1d)
print(cm)

[[  201     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     5     0     0     0     0     0     0     0     0     2     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0    11     0     0     0     0     0     0     0     3     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     2     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0   737     0     0     0     0     6     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     1     0     0     1     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0     0     2     0
      0     0     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0  8238     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0   296     2     0
      0     0     0     0     0     0     0     0     0     0]
 [    6     0     0     0     1     1     0     0     0     0 13376     0
      0     0     0     0     0     0     0     0     2     0]
 [    0     0     0     0     0     0     0     0     0     0     1     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      1     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      0    36     0     0     0     0     0     0     0     0]
 [    3     0     0     0     0     0     0     0     0     0     1     0
      0     0   579     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     2     0
      0     0     0     0     0     0     0     0     0     0]
 [    4     0     0     0     0     0     0     0     0     0     4     0
      0     0     0     0   741     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0   551     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     1     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0   196     0     0]
 [    0     0     0     0     0     0     0     0     0     0     8     0
      0     0     0     0     0     0     0     0   168     0]
 [    1     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     3]]

#Logistic Regression

In [ ]:
print(X_train.shape, X_val.shape, X_test.shape)
print(y_train.shape, y_val.shape, y_test.shape)

(80621, 122) (20156, 122) (25195, 122)
(80621, 23) (20156, 23) (25195, 23)

In [ ]:
#Converting to 1D arrays
y_train_1d = np.argmax(y_train.values, axis=1)
y_val_1d   = np.argmax(y_val.values, axis=1)
y_test_1d  = np.argmax(y_test.values, axis=1)

In [ ]:
from sklearn.linear_model import LogisticRegression


log_clf = LogisticRegression(
    max_iter=1000,
    n_jobs=-1,
    multi_class="multinomial",
    solver="lbfgs"
)
log_clf.fit(X_train, y_train_1d)

y_val_pred_log = log_clf.predict(X_val)
print("Logistic Regression (val):")
print(classification_report(y_val_1d, y_val_pred_log))

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Logistic Regression (val):
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       143
           1       0.75      0.75      0.75         4
           2       0.00      0.00      0.00         2
           3       1.00      1.00      1.00         7
           4       1.00      0.50      0.67         2
           5       0.97      0.97      0.97       591
           6       1.00      0.50      0.67         2
           7       0.00      0.00      0.00         1
           9       1.00      1.00      1.00      6590
          10       0.93      0.96      0.94       203
          11       0.99      0.99      0.99     10798
          12       0.00      0.00      0.00         1
          14       1.00      1.00      1.00        31
          15       0.99      0.99      0.99       471
          16       0.00      0.00      0.00         1
          17       0.98      0.95      0.96       569
          18       0.98      1.00      0.99       454
          20       1.00      1.00      1.00       147
          21       0.82      0.82      0.82       136
          22       1.00      0.67      0.80         3

    accuracy                           0.99     20156
   macro avg       0.77      0.70      0.73     20156
weighted avg       0.99      0.99      0.99     20156

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
y_test_pred_log = log_clf.predict(X_test)
print("Logistic Regression (test):")
print(classification_report(y_test_1d, y_test_pred_log))

Logistic Regression (test):
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       201
           1       0.67      0.57      0.62         7
           3       0.92      0.79      0.85        14
           4       1.00      1.00      1.00         2
           5       0.96      0.97      0.97       743
           6       0.50      0.50      0.50         2
           7       1.00      0.33      0.50         3
           8       0.00      0.00      0.00         1
           9       1.00      1.00      1.00      8238
          10       0.91      0.96      0.94       298
          11       0.99      0.99      0.99     13386
          12       0.00      0.00      0.00         1
          13       1.00      1.00      1.00         1
          14       1.00      0.97      0.99        36
          15       0.99      0.99      0.99       583
          16       0.00      0.00      0.00         2
          17       0.98      0.96      0.97       749
          18       0.99      1.00      0.99       551
          19       0.00      0.00      0.00         1
          20       1.00      1.00      1.00       196
          21       0.78      0.83      0.80       176
          22       1.00      0.75      0.86         4

    accuracy                           0.99     25195
   macro avg       0.76      0.71      0.72     25195
weighted avg       0.99      0.99      0.99     25195

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Confusion Matrix

In [ ]:
print(confusion_matrix(y_test_1d, y_test_pred_log))

[[  195     0     0     0     0     0     0     0     0     0     6     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     4     0     0     0     0     0     0     0     0     2     0
      0     0     0     0     0     0     0     0     1     0]
 [    0     0    11     0     0     0     0     0     0     0     3     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     2     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0   723     0     0     0     0    13     7     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     1     0     0     1     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     1     0     0     0     0     1     0     0     0     1     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     1     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0  8238     0     0     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     2     0     0     0     0   287     2     0
      0     0     0     0     7     0     0     0     0     0]
 [    6     1     1     0    28     1     0     0     3    10 13281     0
      0     0     4     0     4     7     0     0    40     0]
 [    0     0     0     0     0     0     0     0     0     0     1     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      1     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     1     0
      0    35     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     5     0
      0     0   576     0     2     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     2     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     4    28     0
      0     0     0     0   717     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0   551     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     1     0
      0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0   196     0     0]
 [    0     0     0     0     0     0     0     0     0     0    30     0
      0     0     0     0     0     0     0     0   146     0]
 [    0     0     0     0     0     0     0     0     0     0     1     0
      0     0     0     0     0     0     0     0     0     3]]